// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDufYmX2gBSh-S6peEIDG8YmOwdAMeLbwE',
    appId: '1:171465684664:web:8b04cb2516c6d7370aa64d',
    messagingSenderId: '171465684664',
    projectId: 'sfit-cd995',
    authDomain: 'sfit-cd995.firebaseapp.com',
    storageBucket: 'sfit-cd995.appspot.com',
    measurementId: 'G-SP62ZKX2XD',
    databaseURL: 'https://sfit-cd995-default-rtdb.firebaseio.com'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYee9p6Dew1q0f59m2fuYI0aK54X8xIUI',
    appId: '1:171465684664:android:38635c98d4dc93450aa64d',
    messagingSenderId: '171465684664',
    projectId: 'sfit-cd995',
    storageBucket: 'sfit-cd995.appspot.com',
    databaseURL: 'https://sfit-cd995-default-rtdb.firebaseio.com/'
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiGi5vxLHAYaiH9kLXWLyRZ1R8I1MHtkk',
    appId: '1:171465684664:ios:6f23e613c53ddd360aa64d',
    messagingSenderId: '171465684664',
    projectId: 'sfit-cd995',
    storageBucket: 'sfit-cd995.appspot.com',
    iosBundleId: 'com.example.sfit',
    databaseURL: 'https://sfit-cd995-default-rtdb.firebaseio.com/'
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiGi5vxLHAYaiH9kLXWLyRZ1R8I1MHtkk',
    appId: '1:171465684664:ios:c3dad2e86f3d32e10aa64d',
    messagingSenderId: '171465684664',
    projectId: 'sfit-cd995',
    storageBucket: 'sfit-cd995.appspot.com',
    iosBundleId: 'com.example.sfit.RunnerTests',
    databaseURL: 'https://sfit-cd995-default-rtdb.firebaseio.com/'
  );
}
